### ISSUE TITLE
[DEV] Update `collect` to store network interfaces in SMD

### ISSUE THREAD

**Issue by davidallendj** [OpenCHAMI/magellan#29]
**Short Description**
We will need to store all of the network interfaces to know whether it is infiniband or not. The main concern with Magellan is to confirm that the network interfaces are included in the output of the `collect` command. Additionally, the function in SMD that parses and stores the data received from Magellan will have to be updated to store the network interfaces as well.

**Definition of Done**
This issue will be complete once it is confirmed that Magellan is including the network interfaces in the `collect` subcommand's output that is being sent to SMD. Modifying SMD to handle the new output is outside of the scope of this issue.

**Comment by davidallendj** [comment]
Sure, go for it!

**Comment by cjh1** [comment]
@davidallendj So I have basics of this working. Extracting the networking interface ( names and description ). If the aim is to identify infiniband interfaces we probably need to include network device function, network adapter and/or network port information?

**Comment by cjh1** [comment]
Yes, they are all available through Redfish. I think any of the three would allow one to tell the "type" of network interface. I take a stab at coming up with something for others to comment on.

**Comment by cjh1** [comment]
> Check out https://github.com/OpenCHAMI/magellan/blob/main/pkg/crawler/main.go which has some reference implementation for pulling EthernetInterface details.

Thanks, the NetworkInterface object is pretty sparse ( basically links to other objects ), so it a question of determining what to include.

**Comment by davidallendj** [comment]
Out of curiosity, do you have any other systems to test on? I'm wondering if the NetworkInterface would be the same or similar between different hardware or Redfish implementations. It's an issue we've ran into before where the Redfish implementations were different enough to require checking more thoroughly for them.

**Comment by cjh1** [comment]
The only thing I have been testing against is: https://github.com/Cray-HPE/csm-redfish-interface-emulator. Which has multiple examples, but their not "real" systems.

**Comment by davidallendj** [comment]
Ah, that's right. I can test things out on our hardware once you have something ready.
